# Options: [text, image]
mode: text
# Options: [class]
label_type: class

# Directory containing data
source: data/raw
# CSV with current labels
initial: data/input_labels.csv
# CSV to output final labels
out: data/output_labels.csv

# Number of samples to obtain labels for between each retraining
interval: 5
